md file
cd file
git clone https://github.com/vonwenm/archivex.git
git clone https://github.com/vonwenm/atime.git
git clone https://github.com/vonwenm/autoio.git
git clone https://github.com/vonwenm/csv.git
git clone https://github.com/vonwenm/csv2vcf.git
git clone https://github.com/vonwenm/csv4g.git
git clone https://github.com/vonwenm/docx.git
git clone https://github.com/vonwenm/enforced.git
git clone https://github.com/vonwenm/excel.git
git clone https://github.com/vonwenm/file-filter.git
git clone https://github.com/vonwenm/filer.git
git clone https://github.com/vonwenm/file-reconstructor-golang.git
git clone https://github.com/vonwenm/fileRemove.git
git clone https://github.com/vonwenm/files.git
git clone https://github.com/vonwenm/filesync.git
git clone https://github.com/vonwenm/FileTransferAPIs-Golang.git
git clone https://github.com/vonwenm/fileutil.git
git clone https://github.com/vonwenm/fileutil-1.git
git clone https://github.com/vonwenm/fnlog.git
git clone https://github.com/vonwenm/fsnotify.git
git clone https://github.com/vonwenm/ft-ftw.git
git clone https://github.com/vonwenm/gg.git
git clone https://github.com/vonwenm/go-assets.git
git clone https://github.com/vonwenm/go-assets-builder.git
git clone https://github.com/vonwenm/go-backup.git
git clone https://github.com/vonwenm/gobackup2.git
git clone https://github.com/vonwenm/gobytes.git
git clone https://github.com/vonwenm/go-cp.git
git clone https://github.com/vonwenm/godes.git
git clone https://github.com/vonwenm/go-file.git
git clone https://github.com/vonwenm/Go-File-Encryption-AES.git
git clone https://github.com/vonwenm/GoFS.git
git clone https://github.com/vonwenm/golang_fileserver.git
git clone https://github.com/vonwenm/GoLang-File-Backup.git
git clone https://github.com/vonwenm/golang-filelog.git
git clone https://github.com/vonwenm/golang-filestorage.git
git clone https://github.com/vonwenm/golang-image-ico.git
git clone https://github.com/vonwenm/golang-monitor-file.git
git clone https://github.com/vonwenm/golang-removedir.git
git clone https://github.com/vonwenm/go-localstore.git
git clone https://github.com/vonwenm/gosync.git
git clone https://github.com/vonwenm/gotransfer.git
git clone https://github.com/vonwenm/go-xmlproc.git
git clone https://github.com/vonwenm/grib.git
git clone https://github.com/vonwenm/he.git
git clone https://github.com/vonwenm/jailer.git
git clone https://github.com/vonwenm/LiftBall.git
git clone https://github.com/vonwenm/log_gz_unzip_daemon.git
git clone https://github.com/vonwenm/magic.git
git clone https://github.com/vonwenm/mediatype.git
git clone https://github.com/vonwenm/mirrorfs.git
git clone https://github.com/vonwenm/odf.git
git clone https://github.com/vonwenm/ole2.git
git clone https://github.com/vonwenm/OnixParser.git
git clone https://github.com/vonwenm/PekkersFileSerber.git
git clone https://github.com/vonwenm/RestfulApiMaker.git
git clone https://github.com/vonwenm/safe-renamer.git
git clone https://github.com/vonwenm/saxlike.git
git clone https://github.com/vonwenm/spion.git
git clone https://github.com/vonwenm/statdir.go.git
git clone https://github.com/vonwenm/tail.git
git clone https://github.com/vonwenm/tecutils.git
git clone https://github.com/vonwenm/vfs.git
git clone https://github.com/vonwenm/wasp.git
git clone https://github.com/vonwenm/writefile.git
git clone https://github.com/vonwenm/xlsx.git
git clone https://github.com/vonwenm/xml2json.git
git clone https://github.com/vonwenm/XMLGen.git
git clone https://github.com/vonwenm/xopen.git
